version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: notes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: notes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  quarkus:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: notes-app
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/notes
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: 123456
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
