name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quarkus_crud
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@v1
        with:
          kotlin-version: '2.0.21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            nc -z 127.0.0.1 3306 && echo "MySQL is up!" && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run tests
        env:
          QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://localhost:3306/quarkus_crud
          QUARKUS_DATASOURCE_USERNAME: root
          QUARKUS_DATASOURCE_PASSWORD: root
          QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
        run: mvn verify
